### ISSUE TITLE
Cart details in the main page

### ISSUE THREAD

**Issue by henriquecrang** [DiogoZdev/ZBurger#1]
It would be great if the user could see in main page some information about the cart. It could be the number of items or the price. This information would also be useful as a feedback for the user indicating that clicking in the "+" worked. In the way it is now, the user needs to click "Sacola" to check if something changed after adding a new item.

**Comment by DiogoZdev** [comment]
Thank you for the feedback. The bag item-counter feature was implemented into the project. You may test it directly through: https://diogozdev.github.io/projects/zburger/

Here it goes a preview:

![image](https://user-images.githubusercontent.com/56682712/127756011-6e682cdf-a38d-4f02-a68c-25a6364faf67.png)
